secrets:
  mysql_password: 
    file: ../secrets/mysql_password
  mysql_root_password: 
    file: ../secrets/mysql_root_password
  wp_admin_password: 
    file: ../secrets/wp_admin_password
  wp_user_password: 
    file: ../secrets/wp_user_password
  
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/qalpesse/data/wordpress:/var/www/html
    networks:
        - inception
    depends_on:
      - wp-php
      - mariadb
    restart: always
  wp-php:
    build: requirements/wordpress/.
    container_name: wp-php
    secrets:
      - mysql_password
      - mysql_root_password
      - wp_admin_password
      - wp_user_password
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - /home/qalpesse/data/wordpress:/var/www/html
    networks:
        - inception
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    secrets:
      - mysql_password
      - mysql_root_password
    env_file: .env
    volumes:
      - /home/qalpesse/data/mysql:/var/lib/mysql
    networks:
        - inception
    restart: always

networks:
  inception:
    driver: bridge
