services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
    networks:
        - internal
    depends_on:
      - wp-php
      - mariadb
  wp-php:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    networks:
        - internal
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
        - internal
networks:
  internal:
    driver: bridge
